### ISSUE TITLE
请问15k数据是完整的吗？

### ISSUE THREAD

**Issue by MrYxJ** [nju-websoft/JAPE#5]
请问15k数据里 triples, training_attrs 数目比论文Table 1  Rel.triples, Atr.triples 少，是没有全部放出来吗？

**Comment by sunzequn** [comment]
你好，之前的这个[issue](https://github.com/nju-websoft/JAPE/issues/2)里面我回答过了类似问题，你可以参考一下，如果有问题，继续联系我。

**Comment by MrYxJ** [comment]
> 
> 
> 你好，之前的这个[issue](https://github.com/nju-websoft/JAPE/issues/2)里面我回答过了类似问题，你可以参考一下，如果有问题，继续联系我。

**Comment by MrYxJ** [comment]
感谢回复，您的意思是论文表格的Rel.triples和Atr_triples是根据15k条对齐的实体抽取的全部三元组数目，但考虑贡献性，实验的数据只选了一部分。这样理解对吗？

**Comment by sunzequn** [comment]
是的。
