### ISSUE TITLE
The ensemble method of translation model and JAPE

### ISSUE THREAD

**Issue by acharkq** [nju-websoft/JAPE#6]
Your JAPE paper has conducted ensemble experiment on google translation and JAPE models as said in the blue highlighted text below:
![Screenshot from 2019-08-27 21-46-51](https://user-images.githubusercontent.com/34520988/63776568-3b201d00-c914-11e9-8305-bbc3327bd91b.png)
But I can not quite understand your ensemble method. What does it mean by
```txt
for each latent aligned entities, we considered the lower rank of the two results as the combined rank
```
Besides, I can not find the corresponding code in this repository. Could you please help me out here?

**Comment by sunzequn** [comment]
Sorry for this somewhat vague expression. Here our goal is to see whether the embedding-based and translation-based methods are complementary to each other. For a source entity to be aligned, we can get two ranks of its reference target counterpart using the two methods. Then we choose the lower rank as the final result to compute Hits@k and MRR scores. Thus, it is not an ensemble method. It is, in fact, just an experimental study. For ensemble methods, we have tried combining the similarities from the two methods, also yielding promising results.

**Comment by acharkq** [comment]
Thanks for the help!
