### ISSUE TITLE
Interpretation of output

### ISSUE THREAD

**Issue by Vika-meow** [nju-websoft/JAPE#8]
Hi!
I tried to use this model and run se_pos.py, attr2vec.py and ent2vec_sparce.py. So, I have output files attr_embeddings, attrs_meta, attrs_vec.npy, ents_embeddings_1,  ents_embeddings_2, ents_sim.mtx, ent_vec_1.npy, ent_vec_2.npy, kb1_ents_sim.mtx, kb2_ents_sim.mtx.
Can you help me to understand their meaning and explain how do you analyze results?

Best wishes, Vika

**Comment by sunzequn** [comment]
Hi Vika,

Sorry for my late reply,  and thanks for your interest in our work.

"attr_embeddings", "attrs_vec.npy", "ents_embeddings_1" and "ents_embeddings_2" are the output embeddings of attributes or entities.

"ents_sim.mtx" is the pair-wise similarity matrix (calculated based on attribute embeddings) between the source KG's entities and the target entities.

"kb1_ents_sim.mtx" is the pair-wise similarity matrix (calculated based on attribute embeddings) between the source KG's entities.

**Comment by Vika-meow** [comment]
Sorry for my late reply. 
Your answer is very helpful, thank you!
